import Head from 'next/head'
import {useGetProductQuery} from '../../store/services/product'
import {GetStaticPaths, GetStaticProps, NextPage} from 'next'
import ProductDescription from '../../components/product/ProductDescription'
import ProductReviews from '../../components/product/ProductReviews'
import ProductGallery from '../../components/product/ProductGallery'
import ProductDetails from '../../components/product/ProductDetails'

interface ProductPageProps {
  id: string
}

const css = {
  main: 'py-12 sm:py-16',
  inner: 'max-w-site mx-auto px-4',
  product: 'lg:grid lg:grid-cols-2 lg:gap-20 lg:items-center',
  media: 'lg:max-width-[none] mb-10 sm:mb-12 md:mb-14 lg:mb-0',
  body: 'max-w-2xl mx-auto w-full',
}

const ProductPage: NextPage<ProductPageProps> = ({id}) => {
  const {data, isLoading} = useGetProductQuery(id)
  const {product} = data || {}
  const {description, numOfReviews, reviews} = product || {}

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={css.main}>
        <div className={css.inner}>
          <div className={css.product}>
            <div className={css.media}>
              <ProductGallery product={product} isLoading={isLoading} />
            </div>
            <div className={css.body}>
              <ProductDetails product={product} isLoading={isLoading} />
            </div>
          </div>
          {!isLoading && (
            <>
              <ProductDescription description={description} />
              <ProductReviews product={product} />
            </>
          )}
        </div>
      </div>
    </div>
  )
}

export const getStaticProps: GetStaticProps = ({params}) => {
  const {id} = params as any
  return {
    props: {
      id,
    },
  }
}

export const getStaticPaths: GetStaticPaths = () => {
  return {
    paths: [],
    fallback: 'blocking',
  }
}

export default ProductPage
