import type {NextPage} from 'next'
import Head from 'next/head'
import {useState} from 'react'
import Paginate from '../components/Paginate'
import ProductGrid from '../components/product/ProductGrid'
import {ResultsFound, ResultsLoading, ResultsNotFound} from '../components/ResultsLabel'
import ProductFilters from '../components/product/ProductFilters'
import Hero from '../components/elements/Hero'
import {useGetAllProductsQuery} from '../store/services/product'
import {IProductFilter} from '../types/product'

const css = {
  main: 'max-w-site mx-auto px-4',
  grid: 'grid md:grid-cols-12 gap-10 pb-12 sm:pb-16',
  body: 'md:col-span-9 md:order-2',
  results: 'relative max-w-lg mx-auto px-4 flex justify-center',
  resultsIcon: 'w-32 text-gray-200',
  resultsText: 'absolute text-2xl left-0 top-1/2 -translate-y-1/2 w-full text-center text-gray-700',
  title: 'font-medium mb-6 text-center sm:text-left text-4xl uppercase',
}

const QUERY_FILTER = {
  limit: 6,
}

const ShopPage: NextPage = () => {
  const [filter, setFilter] = useState<IProductFilter>(QUERY_FILTER)
  const {data, isLoading} = useGetAllProductsQuery(filter)
  const {found = 0, total = 0, pages = 1, page = 1, products = []} = data || {}

  const ShowResults = () => {
    if (isLoading) {
      return (
        <ResultsLoading>
          <ProductGrid data={[]} isLoading={true} skeletons={filter.limit} withSidebar={true} />
        </ResultsLoading>
      )
    }
    if (found) {
      return (
        <ResultsFound page={page} found={found} limit={QUERY_FILTER.limit} total={total}>
          <ProductGrid isLoading={false} data={products} withSidebar={true} />
        </ResultsFound>
      )
    }
    return <ResultsNotFound />
  }

  return (
    <div>
      <Head>
        <title>Shop - Furniture Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={css.main}>
        <Hero title="Our Shop" />
        <div className={css.grid}>
          <ProductFilters filter={filter} setFilter={setFilter} />
          <div className={css.body}>
            <ShowResults />
            <Paginate
              setFilter={setFilter}
              pages={!isLoading && pages > 1 ? pages : 0}
              page={page}
            />
          </div>
        </div>
      </div>
    </div>
  )
}

export default ShopPage
